### PR TITLE
Final commit

### PR DESCRIPTION
**Pull request by MK-Kwon**
Hi Pete,

I made a mistake and wasn't able to create a new pull request for all my previous commits. Git kept saying there isn't anything to compare so I just got my final files. If you'd like to check out all the commit history please visit my forked repository. 
Sorry :( 

This one is the final with all five tasks being done as required. If there are any issues with the code or any changes that need to be made please let me know!

Best regards,
Min

### CODE REVIEW

**Comment by peterblunden-egrowcery** [comment]
Hi Min, thanks for taking the time to do this. Your code doesn't look bad overall but there some issues with this PR 
* Why did you fork the repository and not just branch within this one? Was it a permissions issue? You could have just created a single branch and done all your work in there.
* There are conflicts all the way through the code - you need to resolve the conflicts before pushing / merging. Do you need help with this?
* You've brought in a lot of new dependencies such as bootstrap and boostrap-tables, you shouldnt have needed any of those. A lot of this seems to be related to your new component TableMain, which isnt actually used in the app as far as I can see?

Pete

**Comment by MK-Kwon** [comment]
Hi Pete,

Thanks for the advice.


  *   Forking : I actually tried to clone the repo and create a branch directly to your repo but my access was denied. I just thought forking was the right way and it wasn't! Looks like I need permission from you to create a branch.


  *   Merge conflicts: My bad. As I wasn't starting from a branch on your repo when I tried to make a PR from my forked repo it just didn't work. I rebased my last commit and the whole merge conflicts appeared. I will create a branch and push commits there properly once I'm permitted.


  *    Dependencies: Also my bad. I initially designed the app a bit differently and installed a bunch of dependencies and never ended up using any of them. I will remove all of those and only leave what is needed before I make my next PR.

Please let me know if I'm required to do anything else. 🙂

Regards,
Min

________________________________

**Comment by MK-Kwon** [comment]
FYI








________________________________

**Comment by peterblunden-egrowcery** [comment]
@MK-Kwon ok no problem. Apologies if i didnt set up the permissions right. Stick with your forked version now that its there, if you can just clean up the conflicts and remove any dependencies you don't need then i can review with the team thanks!

**Pull request closed without merging**
